import Vue from 'vue'
import { button, NavBar, Field, Cell, CellGroup, Toast,
  CountDown, Tabbar, TabbarItem, Image, Grid, GridItem, Icon, Dialog, Tab, Tabs, PullRefresh, List, Popup, SwipeCell, Search } from 'vant'

Vue.use(button)
Vue.use(NavBar)
Vue.use(Field)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Toast)
Vue.use(CountDown)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Icon)
Vue.use(Image)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Dialog)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(PullRefresh)
Vue.use(List)
Vue.use(Popup)
Vue.use(SwipeCell)
Vue.use(Search)
